// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calcCounts
Rcpp::List calcCounts(const Rcpp::IntegerVector& xInd, const Rcpp::IntegerVector& yInd, const Rcpp::NumericMatrix& kernRatio, const Rcpp::NumericVector& kernRatioVec, const Rcpp::NumericVector& kernTrueNormVec, const Rcpp::NumericVector& kernFalseNormVec);
RcppExport SEXP _phylocorrpkg_calcCounts(SEXP xIndSEXP, SEXP yIndSEXP, SEXP kernRatioSEXP, SEXP kernRatioVecSEXP, SEXP kernTrueNormVecSEXP, SEXP kernFalseNormVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type xInd(xIndSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type yInd(yIndSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type kernRatio(kernRatioSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type kernRatioVec(kernRatioVecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type kernTrueNormVec(kernTrueNormVecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type kernFalseNormVec(kernFalseNormVecSEXP);
    rcpp_result_gen = Rcpp::wrap(calcCounts(xInd, yInd, kernRatio, kernRatioVec, kernTrueNormVec, kernFalseNormVec));
    return rcpp_result_gen;
END_RCPP
}
// calcPMF2d
Rcpp::NumericVector calcPMF2d(const Rcpp::IntegerVector& xInd, const Rcpp::IntegerVector& yInd, const Rcpp::NumericMatrix& PMFmat);
RcppExport SEXP _phylocorrpkg_calcPMF2d(SEXP xIndSEXP, SEXP yIndSEXP, SEXP PMFmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type xInd(xIndSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type yInd(yIndSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type PMFmat(PMFmatSEXP);
    rcpp_result_gen = Rcpp::wrap(calcPMF2d(xInd, yInd, PMFmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phylocorrpkg_calcCounts", (DL_FUNC) &_phylocorrpkg_calcCounts, 6},
    {"_phylocorrpkg_calcPMF2d", (DL_FUNC) &_phylocorrpkg_calcPMF2d, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_phylocorrpkg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
