# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcCounts <- function(xInd, yInd, kernRatio, kernRatioVec, kernTrueNormVec, kernFalseNormVec) {
    .Call('_phylocorrpkg_calcCounts', PACKAGE = 'phylocorrpkg', xInd, yInd, kernRatio, kernRatioVec, kernTrueNormVec, kernFalseNormVec)
}

calcPMF2d <- function(xInd, yInd, PMFmat) {
    .Call('_phylocorrpkg_calcPMF2d', PACKAGE = 'phylocorrpkg', xInd, yInd, PMFmat)
}

